from __future__ import annotations

class_map = {
    1: "spleen",
    2: "kidney_right",
    3: "kidney_left",
    4: "gallbladder",
    5: "liver",
    6: "stomach",
    7: "aorta",
    8: "inferior_vena_cava",
    9: "portal_vein_and_splenic_vein",
    10: "pancreas",
    11: "adrenal_gland_right",
    12: "adrenal_gland_left",
    13: "lung_upper_lobe_left",
    14: "lung_lower_lobe_left",
    15: "lung_upper_lobe_right",
    16: "lung_middle_lobe_right",
    17: "lung_lower_lobe_right",
    18: "vertebrae_L5",
    19: "vertebrae_L4",
    20: "vertebrae_L3",
    21: "vertebrae_L2",
    22: "vertebrae_L1",
    23: "vertebrae_T12",
    24: "vertebrae_T11",
    25: "vertebrae_T10",
    26: "vertebrae_T9",
    27: "vertebrae_T8",
    28: "vertebrae_T7",
    29: "vertebrae_T6",
    30: "vertebrae_T5",
    31: "vertebrae_T4",
    32: "vertebrae_T3",
    33: "vertebrae_T2",
    34: "vertebrae_T1",
    35: "vertebrae_C7",
    36: "vertebrae_C6",
    37: "vertebrae_C5",
    38: "vertebrae_C4",
    39: "vertebrae_C3",
    40: "vertebrae_C2",
    41: "vertebrae_C1",
    42: "esophagus",
    43: "trachea",
    44: "heart_myocardium",
    45: "heart_atrium_left",
    46: "heart_ventricle_left",
    47: "heart_atrium_right",
    48: "heart_ventricle_right",
    49: "pulmonary_artery",
    50: "brain",
    51: "iliac_artery_left",
    52: "iliac_artery_right",
    53: "iliac_vena_left",
    54: "iliac_vena_right",
    55: "small_bowel",
    56: "duodenum",
    57: "colon",
    58: "rib_left_1",
    59: "rib_left_2",
    60: "rib_left_3",
    61: "rib_left_4",
    62: "rib_left_5",
    63: "rib_left_6",
    64: "rib_left_7",
    65: "rib_left_8",
    66: "rib_left_9",
    67: "rib_left_10",
    68: "rib_left_11",
    69: "rib_left_12",
    70: "rib_right_1",
    71: "rib_right_2",
    72: "rib_right_3",
    73: "rib_right_4",
    74: "rib_right_5",
    75: "rib_right_6",
    76: "rib_right_7",
    77: "rib_right_8",
    78: "rib_right_9",
    79: "rib_right_10",
    80: "rib_right_11",
    81: "rib_right_12",
    82: "humerus_left",
    83: "humerus_right",
    84: "scapula_left",
    85: "scapula_right",
    86: "clavicula_left",
    87: "clavicula_right",
    88: "femur_left",
    89: "femur_right",
    90: "hip_left",
    91: "hip_right",
    92: "sacrum",
    93: "face",
    94: "gluteus_maximus_left",
    95: "gluteus_maximus_right",
    96: "gluteus_medius_left",
    97: "gluteus_medius_right",
    98: "gluteus_minimus_left",
    99: "gluteus_minimus_right",
    100: "autochthon_left",
    101: "autochthon_right",
    102: "iliopsoas_left",
    103: "iliopsoas_right",
    104: "urinary_bladder",
    105: "sternum",
    106: "thyroid gland",
    107: "right adrenal gland",
    108: "left adrenal gland",
    109: "right psoas major",
    110: "left psoas major",
    111: "right rectus abdominis",
    112: "left rectus abdominis",
    113: "brainstem",
    114: "spinal canal",
    115: "left parotid gland",
    116: "right parotid gland",
    117: "left submandibular gland",
    118: "right submandibular gland",
    119: "larynx",
    120: "sigmoid",
    121: "rectum",
    122: "prostate",
    123: "seminal vasicle",
    124: "left mammary gland",
    125: "right mammary gland",
    126: "white matter",
    127: "gray matter",
    128: "csf",
    129: "head bone",
    130: "scalp",
    131: "eye balls",
    132: "compact bone",
    133: "spongy bone",
    134: "blood",
    135: "head muscles",
    136: "OAR_A_Carotid_L",
    137: "OAR_A_Carotid_R",
    138: "OAR_Arytenoid",
    139: "OAR_Bone_Mandible",
    140: "OAR_Brainstem",
    141: "OAR_BuccalMucosa",
    142: "OAR_Cavity_Oral",
    143: "OAR_Cochlea_L",
    144: "OAR_Cochlea_R",
    145: "OAR_Cricopharyngeus",
    146: "OAR_Esophagus_S",
    147: "OAR_Eye_AL",
    148: "OAR_Eye_AR",
    149: "OAR_Eye_PL",
    150: "OAR_Eye_PR",
    151: "OAR_Glnd_Lacrimal_L",
    152: "OAR_Glnd_Lacrimal_R",
    153: "OAR_Glnd_Submand_L",
    154: "OAR_Glnd_Submand_R",
    155: "OAR_Glnd_Thyroid",
    156: "OAR_Glottis",
    157: "OAR_Larynx_SG",
    158: "OAR_Lips",
    159: "OAR_OpticChiasm",
    160: "OAR_OpticNrv_L",
    161: "OAR_OpticNrv_R",
    162: "OAR_Parotid_L",
    163: "OAR_Parotid_R",
    164: "OAR_Pituitary",
    165: "OAR_SpinalCord",
    166: "subcutaneous_tissue",
    167: "muscle",
    168: "abdominal_cavity",
    169: "thoracic_cavity",
    170: "bones",
    171: "glands",
    172: "pericardium",
    173: "breast_implant",
    174: "mediastinum",
    175: "brain_head",
    176: "spinal_cord",
}

class_map_9_parts = {
    # 17 classes part 251
    "class_map_part_organs": {
        1: "spleen",
        2: "kidney_right",
        3: "kidney_left",
        4: "gallbladder",
        5: "liver",
        6: "stomach",
        7: "aorta",
        8: "inferior_vena_cava",
        9: "portal_vein_and_splenic_vein",
        10: "pancreas",
        11: "adrenal_gland_right",
        12: "adrenal_gland_left",
        13: "lung_upper_lobe_left",
        14: "lung_lower_lobe_left",
        15: "lung_upper_lobe_right",
        16: "lung_middle_lobe_right",
        17: "lung_lower_lobe_right",
    },
    # 24 classes part 252
    "class_map_part_vertebrae": {
        1: "vertebrae_L5",
        2: "vertebrae_L4",
        3: "vertebrae_L3",
        4: "vertebrae_L2",
        5: "vertebrae_L1",
        6: "vertebrae_T12",
        7: "vertebrae_T11",
        8: "vertebrae_T10",
        9: "vertebrae_T9",
        10: "vertebrae_T8",
        11: "vertebrae_T7",
        12: "vertebrae_T6",
        13: "vertebrae_T5",
        14: "vertebrae_T4",
        15: "vertebrae_T3",
        16: "vertebrae_T2",
        17: "vertebrae_T1",
        18: "vertebrae_C7",
        19: "vertebrae_C6",
        20: "vertebrae_C5",
        21: "vertebrae_C4",
        22: "vertebrae_C3",
        23: "vertebrae_C2",
        24: "vertebrae_C1",
    },
    # 18 part 253
    "class_map_part_cardiac": {
        1: "esophagus",
        2: "trachea",
        3: "heart_myocardium",
        4: "heart_atrium_left",
        5: "heart_ventricle_left",
        6: "heart_atrium_right",
        7: "heart_ventricle_right",
        8: "pulmonary_artery",
        9: "brain",
        10: "iliac_artery_left",
        11: "iliac_artery_right",
        12: "iliac_vena_left",
        13: "iliac_vena_right",
        14: "small_bowel",
        15: "duodenum",
        16: "colon",
        17: "urinary_bladder",
        18: "face",
    },
    # 21 part 254
    "class_map_part_muscles": {
        1: "humerus_left",
        2: "humerus_right",
        3: "scapula_left",
        4: "scapula_right",
        5: "clavicula_left",
        6: "clavicula_right",
        7: "femur_left",
        8: "femur_right",
        9: "hip_left",
        10: "hip_right",
        11: "sacrum",
        12: "gluteus_maximus_left",
        13: "gluteus_maximus_right",
        14: "gluteus_medius_left",
        15: "gluteus_medius_right",
        16: "gluteus_minimus_left",
        17: "gluteus_minimus_right",
        18: "autochthon_left",
        19: "autochthon_right",
        20: "iliopsoas_left",
        21: "iliopsoas_right",
    },
    # 24 classes part 255
    # 12. ribs start from vertebrae T12
    # Small subset of population (roughly 8%) have 13. rib below 12. rib
    #  (would start from L1 then)
    #  -> this has label rib_12
    # Even smaller subset (roughly 1%) has extra rib above 1. rib   ("Halsrippe")
    #  (the extra rib would start from C7)
    #  -> this has label rib_1
    #
    # Quite often only 11 ribs (12. ribs probably so small that not found). Those
    # cases often wrongly segmented.
    "class_map_part_ribs": {
        1: "rib_left_1",
        2: "rib_left_2",
        3: "rib_left_3",
        4: "rib_left_4",
        5: "rib_left_5",
        6: "rib_left_6",
        7: "rib_left_7",
        8: "rib_left_8",
        9: "rib_left_9",
        10: "rib_left_10",
        11: "rib_left_11",
        12: "rib_left_12",
        13: "rib_right_1",
        14: "rib_right_2",
        15: "rib_right_3",
        16: "rib_right_4",
        17: "rib_right_5",
        18: "rib_right_6",
        19: "rib_right_7",
        20: "rib_right_8",
        21: "rib_right_9",
        22: "rib_right_10",
        23: "rib_right_11",
        24: "rib_right_12",
    },
    # 21 classes organs at risk in house and visceral
    # part 256
    "class_map_part_oarrad": {
        1: "sternum",
        2: "thyroid gland",
        3: "right adrenal gland",
        4: "left adrenal gland",
        5: "right psoas major",
        6: "left psoas major",
        7: "right rectus abdominis",
        8: "left rectus abdominis",
        9: "brainstem",
        10: "spinal canal",
        11: "left parotid gland",
        12: "right parotid gland",
        13: "left submandibular gland",
        14: "right submandibular gland",
        15: "larynx",
        16: "sigmoid",
        17: "rectum",
        18: "prostate",
        19: "seminal vasicle",
        20: "left mammary gland",
        21: "right mammary gland",
    },
    ##10 classes head koens registration
    ## part 257
    "class_map_part_head": {
        1: "white matter",
        2: "gray matter",
        3: "csf",
        4: "head bone",
        5: "scalp",
        6: "eye balls",
        7: "compact bone",
        8: "spongy bone",
        9: "blood",
        10: "head muscles",
    },
    ## 30 lasses Head and neck structures from HanSeg
    ## part 258
    "class_map_part_headneck": {
        1: "OAR_A_Carotid_L",
        2: "OAR_A_Carotid_R",
        3: "OAR_Arytenoid",
        4: "OAR_Bone_Mandible",
        5: "OAR_Brainstem",
        6: "OAR_BuccalMucosa",
        7: "OAR_Cavity_Oral",
        8: "OAR_Cochlea_L",
        9: "OAR_Cochlea_R",
        10: "OAR_Cricopharyngeus",
        11: "OAR_Esophagus_S",
        12: "OAR_Eye_AL",
        13: "OAR_Eye_AR",
        14: "OAR_Eye_PL",
        15: "OAR_Eye_PR",
        16: "OAR_Glnd_Lacrimal_L",
        17: "OAR_Glnd_Lacrimal_R",
        18: "OAR_Glnd_Submand_L",
        19: "OAR_Glnd_Submand_R",
        20: "OAR_Glnd_Thyroid",
        21: "OAR_Glottis",
        22: "OAR_Larynx_SG",
        23: "OAR_Lips",
        24: "OAR_OpticChiasm",
        25: "OAR_OpticNrv_L",
        26: "OAR_OpticNrv_R",
        27: "OAR_Parotid_L",
        28: "OAR_Parotid_R",
        29: "OAR_Pituitary",
        30: "OAR_SpinalCord",
    },
    ## 11 claases for body parts including subcutaneous tissue
    ## part 259
    "class_map_part_bodyregions": {
        1: "subcutaneous_tissue",
        2: "muscle",
        3: "abdominal_cavity",
        4: "thoracic_cavity",
        5: "bones",
        6: "glands",
        7: "pericardium",
        8: "breast_implant",
        9: "mediastinum",
        10: "brain",
        11: "spinal_cord",
    },
}

# map_taskid_to_partname = {
#     251: "class_map_part_organs",
#     252: "class_map_part_vertebrae",
#     253: "class_map_part_cardiac",
#     254: "class_map_part_muscles",
#     255: "class_map_part_ribs"
# }

map_taskid_to_partname = {
    251: "class_map_part_organs",
    252: "class_map_part_vertebrae",
    253: "class_map_part_cardiac",
    254: "class_map_part_muscles",
    255: "class_map_part_ribs",
    256: "class_map_part_oarrad",
    257: "class_map_part_head",
    258: "class_map_part_headneck",
    259: "class_map_part_bodyregions",
}
except_labels_combine = [
    "OAR_Brainstem",
    "brain",  # place for gray-white matter
    "bone",  # place for vertebrae
    "OAR_Parotid_L",  # included in visceral
    "OAR_Parotid_R",  # included in visceral
    "OAR_Glnd_Submand_L",  # included in visceral
    "OAR_Glnd_Submand_R",  # included in visceral
    "OAR_Glnd_Thyroid",  # included in visceral
    "OAR_Larynx_SG",  # included in visceral
    "right adrenal gland",  # included in totalseg
    "left adrenal gland",  # included in totalseg
    "OAR_Esophagus_S",  # included in totalseg
    "face",  # for visualization
    "glands",  # from saros
    "head bone",  # overlaps with hanseg structures
    "scalp",  # cover all head structures
    "eye balls",  # repeated in hanseg
    "compact bone",  # overlaps with hanseg structures
    "spongy bone",  # overlaps with hanseg structures
    "blood",  # overlaps with hanseg structures
    "head muscles",  # overlaps with hanseg structures
    "muscle",
    "abdominal_cavity",
    "bones",  # overlaps for vertebrae
    "glands",
    "pericardium",
    "breast_implant",
    "mediastinum",
    "spinal_cord",
]
